import React from 'react';
import { Receipt } from '../types';
import { Button } from './Button';
import { X, Printer } from 'lucide-react';

interface ReceiptModalProps {
  receipt: Receipt;
  onClose: () => void;
}

export const ReceiptModal: React.FC<ReceiptModalProps> = ({ receipt, onClose }) => {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50 p-4 no-print">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-lg overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header - No Print */}
        <div className="p-4 border-b flex justify-between items-center bg-gray-50">
          <h3 className="font-semibold text-gray-800">Print Preview</h3>
          <button onClick={onClose} className="text-gray-500 hover:text-gray-700">
            <X size={20} />
          </button>
        </div>

        {/* Scrollable Content */}
        <div className="p-6 overflow-y-auto flex-1">
          {/* Printable Area - Identified by class for print media query */}
          <div className="print-area bg-white border-2 border-gray-800 p-8 rounded-sm text-gray-900">
            <div className="text-center mb-6">
              <h1 className="text-3xl font-bold uppercase tracking-wider mb-2">Hari PG</h1>
              <p className="text-sm text-gray-600">Luxury Men's Hostel & Accommodation</p>
              <p className="text-xs text-gray-500 mt-1">29, PR Layout, Chandra Layout, Marathahalli, Bengaluru</p>
              <p className="text-xs text-gray-500">Tel: +91 9010646051</p>
            </div>

            <div className="border-t-2 border-b-2 border-gray-200 py-4 mb-6">
              <div className="flex justify-between items-center">
                <span className="font-bold text-lg">RENT RECEIPT</span>
                <span className="text-sm text-gray-600">Date: {new Date(receipt.date).toLocaleDateString()}</span>
              </div>
            </div>

            <div className="space-y-4 text-sm">
              <div className="grid grid-cols-3 gap-4">
                <span className="text-gray-600 font-medium">Received From:</span>
                <span className="col-span-2 font-bold text-lg border-b border-dashed border-gray-300 pb-1">
                  {receipt.residentName}
                </span>
              </div>

              <div className="grid grid-cols-3 gap-4">
                <span className="text-gray-600 font-medium">Room Number:</span>
                <span className="col-span-2 font-semibold border-b border-dashed border-gray-300 pb-1">
                  {receipt.roomNumber}
                </span>
              </div>

              <div className="grid grid-cols-3 gap-4">
                <span className="text-gray-600 font-medium">Mobile No:</span>
                <span className="col-span-2 font-semibold border-b border-dashed border-gray-300 pb-1">
                  {receipt.mobileNumber}
                </span>
              </div>

              <div className="grid grid-cols-3 gap-4 items-center">
                <span className="text-gray-600 font-medium">Amount:</span>
                <span className="col-span-2 font-bold text-xl text-gray-900 border-b border-dashed border-gray-300 pb-1">
                  ₹ {receipt.amount.toLocaleString('en-IN')}
                </span>
              </div>

              {receipt.notes && (
                <div className="grid grid-cols-3 gap-4">
                  <span className="text-gray-600 font-medium">Description:</span>
                  <span className="col-span-2 text-gray-700 italic border-b border-dashed border-gray-300 pb-1">
                    {receipt.notes}
                  </span>
                </div>
              )}
            </div>

            <div className="mt-16 flex justify-between items-end">
              <div className="text-xs text-gray-400">
                <p>Generated by Hari PG App</p>
              </div>
              <div className="text-center">
                <div className="h-10 border-b border-gray-400 w-32 mb-2"></div>
                <p className="text-xs font-bold uppercase">Authorized Signature</p>
              </div>
            </div>
          </div>
        </div>

        {/* Footer Actions - No Print */}
        <div className="p-4 border-t bg-gray-50 flex justify-end space-x-2">
          <Button variant="secondary" onClick={onClose}>Close</Button>
          <Button onClick={handlePrint}>
            <Printer size={16} className="mr-2" /> Print Receipt
          </Button>
        </div>
      </div>
    </div>
  );
};